- src/pages/Home/Home.tsx
This change makes it so you can refresh the `uuid()` of the room before creating a room. Doesn't have much practical utility but since there's room in the textfield for it, why not? Users might want to shuffle their room IDs a few times before creating a room
This is also mobile compatible to 375px width (iPhone SE)
> Add end adornment icon to refresh the room uuid()

- src/components/Shell/ConnectionTestResults.tsx
- src/components/Shell/PeerList.tsx
- src/components/Shell/useConnectionTest.ts
- src/contexts/ShellContext.ts
- src/services/ConnectionTest/ConnectionTest.ts
This PR displays an error when no WebTorrent trackers can be reached.
> feat(connection-test): Display failed tracker connections

- src/components/Shell/ConnectionTestResults.tsx
- src/components/Shell/ServerConnectionFailureDialog.tsx
- src/components/Shell/Shell.tsx
- src/contexts/ShellContext.ts
This PR adds a dialog that is shown when the user clicks the "Server connection failed" message from #129.
> feat(connection-test): [closes #127] Explain tracker connection problems

- src/config/rtcConfig.ts
Updated ICE candidates to use TURN/STUN server based on [violet](https://github.com/paullouisageneau/violet) that uses UDP protocol to establish peer connections. Directly accessing the IP address of the server shows monthly bandwidth usage. Maximum peer connections at the moment is limited to 1000 peers. Tested on local server and everything works as intended.
> updated turn/stun servers

- src/components/Room/RoomFileUploadControls.tsx
This PR fixes #122 by preventing the file upload button from getting stuck when the user cancels out of the file picker UI.
> fix(file-upload): [#122] Prevent file picker from getting stuck

- src/components/Room/MediaButton.tsx
- src/components/Room/RoomAudioControls.tsx
- src/components/Room/RoomFileUploadControls.tsx
- src/components/Room/RoomScreenShareControls.tsx
- src/components/Room/RoomShowMessagesControls.tsx
- src/components/Room/RoomVideoControls.tsx
For #157, this PR improves the styling of the media controls to look more like what users expect from other chat apps.
New design:
<details>
<summary>Old design</summary>
</details>
> feat(media): [closes #157] Improve media button styling

- src/components/Room/RoomAudioControls.tsx
- src/components/Room/RoomVideoControls.tsx
> feat(media): [closes #165] Hide media control selectors when not in use

- package.json
- src/Bootstrap.tsx
For #168, this PR sets the appropriate router `basename` so that clent-side routes work as expected.
> fix(routing): [closes #168] Support GitHub Pages routes

- README.md
- src/components/Shell/Shell.tsx
- src/components/Shell/ShellAppBar.tsx
- src/contexts/ShellContext.ts
- src/models/shell.ts
- src/pages/Home/Home.tsx
For #92, this PR adds support for being embedded into other web apps.
This first iteration is pretty minimal and the code is worth refactoring a bit, but it's good enough for an initial release. Improvements to the UX and code will come in a followup PR.
> feat(embed): [closes #92] Embed support

- src/components/CopyableBlock/CopyableBlock.tsx
- src/components/CopyableBlock/index.ts
- src/components/Message/Message.tsx
- src/components/SyntaxHighlighter/SyntaxHighlighter.tsx
- src/components/SyntaxHighlighter/index.ts
- src/pages/Home/EmbedCodeDialog.tsx
This PR implements a "copy to clipboard" button for code blocks.
[Text copying screencast](https://github.com/jeremyckahn/chitchatter/assets/366330/ed460b7c-5f82-4254-89d5-a708b95d871d)
> feat(ui): Add copy button for code

- src/components/Room/PeerVideo.tsx
- src/components/Room/RoomVideoDisplay.tsx
- src/components/Room/useRoomVideo.ts
For #180, this PR mutes the audio of the `<video />` presenting the user's own screen stream.
> feat(audio) [closes #180] Mute own screen stream

- .github/workflows/label_security_issue.yml
- .github/workflows/security.yml
This PR is a followup to #199. It attempts to fix the labeling of issues created by the ZAProxy scan.
It can only be tested after merging.
> fix(zap_scan): Label issues correctly

- src/components/ChatTranscript/ChatTranscript.tsx
- src/components/Room/Room.tsx
- src/components/Shell/ShellAppBar.tsx
This PR makes some UI improvements:
- It addresses #160 by moving the transcript scrollbar to the edge of the content area
- It improves the display of the room controls
- It removes a redundant button for hiding room controls
[Screencast from 11-23-2023 12:14:43 PM.webm](https://github.com/jeremyckahn/chitchatter/assets/366330/7f0399fe-18f3-42c5-bce1-83f93e298fd9)
> feat(ui) [closes #160] Move transcript scrollbar to content window edge

- src/components/Shell/ShellAppBar.tsx
This PR improves the display of the app bar:
- A divider is added between the QR code and control toggle buttons
- Hovering the room name shows the full room name
> feat(ui) App bar improvements

- src/components/Shell/PeerListItem.tsx
For #217, this PR fixes a regression introduced by #216 that broke the display of the peer volume slider.
> fix(ui): [fixes #217] Give volume slider full width of peer list

- src/components/AudioVolume/AudioVolume.tsx
- src/components/Room/PeerVideo.tsx
- src/components/Room/RoomVideoDisplay.tsx
- src/components/Room/useRoom.ts
- src/components/Room/useRoomAudio.ts
- src/components/Room/useRoomScreenShare.ts
- src/components/Room/useRoomVideo.ts
- src/components/Shell/PeerList.tsx
- src/components/Shell/PeerListItem.tsx
- src/components/Shell/Shell.tsx
- src/contexts/ShellContext.ts
- src/lib/PeerRoom/PeerRoom.ts
- src/models/chat.ts
For #230, this PR implements multichannel audio volume control. It enables users to control the volume for shared screen audio independently from microphone audio from peers.
> feat(audio) [closes #230] Screenshare audio control

- README.md
Assets links are broken when no defined base path for gh-pages and no custom domain are provided as well
Tested here: https://github.com/the-homeless-god/communa/blob/main/vite.config.ts
Works well
> README: Put info about assets links

- README.md
- src/components/ChatTranscript/ChatTranscript.tsx
- src/components/Room/Room.test.tsx
- src/components/Room/Room.tsx
- src/components/Room/TypingStatusBar.tsx
- src/components/Room/usePeerVerification.ts
- src/components/Room/useRoom.ts
- src/components/Room/useRoomAudio.ts
- src/components/Room/useRoomFileShare.ts
- src/components/Room/useRoomScreenShare.ts
- src/components/Room/useRoomVideo.ts
- src/components/Shell/PeerList.tsx
- src/components/Shell/PeerListItem.tsx
- src/components/Shell/RouteContent.tsx
- src/components/Shell/Shell.tsx
- src/contexts/ShellContext.ts
- src/hooks/usePeerAction.ts
- src/lib/PeerRoom/PeerRoom.ts
- src/models/chat.ts
- src/models/network.ts
- src/pages/PrivateRoom/PrivateRoom.tsx
- src/pages/PublicRoom/PublicRoom.tsx
- vite.config.ts
For #141, this PR implements direct message support.
[Screencast of direct message functionality](https://github.com/user-attachments/assets/8cb47b8c-7f00-47eb-a076-2aa1967a5a4c)
> feat(closes #141): Direct messages

- src/pages/Home/Home.tsx
This PR introduces a change to the Home component's room name input field. The input now automatically trims the application's URL prefix from the entered room name. This ensures that users only enter the room name itself, improving usability and preventing accidental inclusion of the URL prefix in the room name.
> feat(home): Trim room name input

- vite.config.ts
At a followup for #481, this PR disables the service worker (the removal of which was reverted in https://github.com/jeremyckahn/chitchatter/commit/1623dd2eca46cdd57ab3264f730ef39c6e433fdb after it was found to break app updates).
This is aligned with this documented approach: https://vite-pwa-org.netlify.app/guide/unregister-service-worker
> feat(app): Safely unregister service worker
