src/Bootstrap.tsx, src/components/Shell/Shell.test.tsx, src/components/Shell/Shell.tsx, src/index.tsx
This PR ensures that users are on up-to-date version of Chitchatter. This is necessary for interoperability between clients as communication interfaces change.
=> feat: [closes #4] App update flow

src/components/MessageForm/MessageForm.tsx
solved #18 limited message to 1000
=> limited message to 1000

src/Bootstrap.test.tsx, src/Bootstrap.tsx, src/components/PeerNameDisplay/PeerNameDisplay.tsx, src/components/PeerNameDisplay/getPeerName.ts, src/components/PeerNameDisplay/index.ts, src/components/Room/Room.tsx, src/contexts/SettingsContext.ts, src/models/settings.ts, src/pages/PublicRoom/PublicRoom.tsx, src/pages/Settings/Settings.tsx, src/services/Notification/Notification.tsx, src/services/Notification/index.ts
For #6, this PR shows a [`Notification`](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) when the user receives a message in the background.
=> feat: [closes #6] Show notifications for messages recieved in the background

package-lock.json, package.json, src/Bootstrap.tsx, src/components/Shell/Drawer.tsx, src/components/Shell/Shell.tsx, src/config/routes.ts, src/index.sass, src/pages/About/About.tsx, src/pages/About/index.sass, src/pages/Disclaimer/Disclaimer.tsx, src/pages/Disclaimer/index.sass, src/pages/Disclaimer/index.ts
For #40, this PR implements a Disclaimer page. Much of the copy was adapted from @MohammadTaseenKhan's work in #39.
=> Disclaimer

README.md, src/components/ChatTranscript/ChatTranscript.tsx, src/components/Room/useRoom.ts, src/models/network.ts, src/pages/About/About.tsx
This PR implements message backfilling for #22.
=> feat: [closes #22] implement message backfilling

README.md, src/Bootstrap.tsx, src/components/PasswordPrompt/PasswordPrompt.tsx, src/components/PasswordPrompt/index.tsx, src/components/Room/Room.tsx, src/components/Room/useRoom.ts, src/config/routes.ts, src/pages/About/About.tsx, src/pages/Home/Home.tsx, src/pages/PrivateRoom/PrivateRoom.tsx, src/pages/PrivateRoom/index.ts
This PR implements private rooms for #3.
=> feat: (closes #3) Private rooms

src/components/Room/Room.tsx, src/components/Room/useRoom.ts, src/services/PeerRoom/PeerRoom.ts
For #19, this PR implements audio communication within chat rooms.
=> feat: (closes #19) Audio calls

src/components/Room/Room.tsx, src/components/Room/RoomAudioControls.tsx, src/components/Room/useRoom.ts, src/components/Room/useRoomAudio.ts, src/services/PeerRoom/PeerRoom.ts
=> refactor: Room audio

src/components/Room/PeerVideo.tsx, src/components/Room/RoomVideoDisplay.tsx
This PR enables users to focus selected videos.
=> feat: Video focusing

package-lock.json, package.json
This PR attempts to automatically reconnect peers by using https://github.com/dmotz/trystero/pull/30.
=> feat: Use trystero@github:jeremyckahn/trystero#bugfix/29__clean-up-peers

package-lock.json, package.json, src/components/Message/InlineMedia.tsx, src/components/Room/RoomFileUploadControls.tsx, src/components/Room/useRoom.ts, src/components/Room/useRoomFileShare.ts, src/components/Shell/PeerDownloadFileButton.tsx, src/services/FileTransfer/FileTransfer.ts, src/setupTests.ts
For #86, this PR implements encrypted file transfers.
=> feat: [closes #86] Encrypted file transfers

src/components/AudioVolume/AudioVolume.tsx, src/components/AudioVolume/index.ts, src/components/Room/useRoomAudio.ts, src/components/Shell/PeerList.tsx, src/components/Shell/Shell.tsx, src/contexts/ShellContext.ts
This PR implements the feature requested by #77.
[Peer audio volume control preview](https://user-images.githubusercontent.com/366330/221446140-52b5e16b-2e8e-4749-ac35-2b1c75534328.webm)
=> feat: [closes #77] Peer audio volume control

.env, package-lock.json, package.json, src/components/Shell/Drawer.tsx
This PR satisfies #94 by displaying the build hash and commit link for the current build.
=> feat: [closes #94] Show build hash

src/components/ChatTranscript/ChatTranscript.tsx, src/components/Room/useRoom.ts, src/components/Shell/Drawer.tsx, src/components/Shell/Shell.tsx, src/components/Shell/ShellAppBar.tsx, src/contexts/ShellContext.ts
This PR gives the chat transcript a reasonable maximum width. It also defaults the sidebars to the open state on wider screens and improves the overall UX related to sidebar open/close states.
=> feat: [closes #110] Wide screen support

src/components/PeerNameDisplay/PeerNameDisplay.tsx, src/components/Room/useRoom.ts, src/components/Shell/PeerList.tsx, src/components/Shell/PeerListItem.tsx, src/components/Shell/Shell.tsx, src/contexts/ShellContext.ts, src/services/PeerRoom/PeerRoom.ts
This PR implements #15 by visually displaying how you are connected to peers.
=> feat: [closes #15] Show connection type

README.md
Update README.md - correct typo - roon -> room
=> Update README.md - correct typo - roon -> room

package-lock.json, package.json, src/__mocks__/trystero/torrent.ts, src/components/Shell/ConnectionTestResults.tsx, src/components/Shell/PeerList.tsx, src/components/Shell/Shell.tsx, src/components/Shell/useConnectionTest.ts, src/contexts/ShellContext.ts, src/services/ConnectionTest/ConnectionTest.ts
This PR updates the sidebar to display the status of WebTorrent tracker connections and when Chitchatter is searching for peers to connect to.
[Connection status demo](https://github.com/jeremyckahn/chitchatter/assets/366330/640737e5-0250-4197-9627-a31c3733f6c4)
=> feat(connection-test): Display tracker connection status

src/components/Shell/EnvironmentUnsupportedDialog.tsx, src/components/Shell/Shell.tsx
For #155, this PR will present a dialog if Chitchatter is running in an unsupported environment.
=> feat(shell): [closes #155]  Handle unsupported environments

README.md, public/404.html
This PR fixes [an issue that resulted](https://github.com/jeremyckahn/chitchatter/issues/168#issuecomment-1741094696) from #169 that should hopefully fully address #168.
=> fix(routing): [closes #168] Construct redirect URL correctly

package-lock.json, package.json, src/components/Room/RoomAudioControls.tsx
This PR introduces Push-to-Talk functionality with the hotkey Ctrl + Shift + S, using the react-hotkeys-hook npm package.
=> Add Push-to-Talk functionality (Issue: 296)

package-lock.json, package.json, src/lib/RoomNameGenerator/RoomNameGenerator.ts, src/lib/RoomNameGenerator/index.ts, src/pages/Home/Home.tsx, src/pages/Home/useHome.tsx
Implemented fix for issue #469
=> added passphrase room names

package-lock.json, package.json
Uses Trystero patch dmotz/trystero#135 to improve room reconnection reliability.
=> feat(dmotz/trystero#135): Use Trystero with reconnection fix
